version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "daily-tao"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vyy26882v05r"
s3_prefix = "daily-tao"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
